import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const mont = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Schnell | Print",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background font-sans antialiased ${mont.className}`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
